// import { Ubuntu } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import Header from "@/components/header/page";
import Sidenav from "@/components/Sidenav/page";
import DashboardLayout from "@/components/DashboardLayout/page";

// const inter = Ubuntu({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {/* <Header />
          <div className="mt-[60px]">{children}</div> */}
          {/* <DashboardLayout> */}
          <div className="">{children}</div>
          {/* </DashboardLayout> */}
        </AuthProvider>
      </body>
    </html>
  );
}
